name: Python Test Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'


    

    # Optional: Install specific dependencies if needed
    # - name: Install dependencies
    #   run: |
    #     pip install pytest  # Example if you need to install pytest or any other library

    - name: Run tests
      run: |
        pytest tests/tools/SentimentAnalysisTool_test.py
        pytest tests/tools/ZapierHookTool_test.py
        pytest tests/tools/EntityRecognitionTool_test.py
Explanation of the Workflow
